### ISSUE TITLE
Unused import of scipy.integrate.trapz is incompatible with current SciPy version

### ISSUE THREAD

**Issue by DavidB256** [grahamgower/moments#1]
Installing `moments` via `mamba install -c bioconda moments` works, but yields an error from the Python code `import moments` due to the absence of the function `scipy.integrate.trapz` from current versions of SciPy. I circumvented this error by reverting to Python v3.8.19 and SciPy v1.10.1. A quick search of the codebase indicates that the function imported at the top of `Spectrum_mod.py` with `from scipy.integrate import trapz` is never actually used, so I believe that this issue could be resolved by simply deleting that line of code. I tried to report this issue on the Bitbucket mirror of this repository, but was met with "This repository does not have issue tracking enabled."

**Comment by grahamgower** [comment]
Hi @DavidB256. This is just a personal fork of moments that I made a while back, in order to contribute a pull request. But I'm not a `moments` developer, and this isn't the main repository. The main repository seems to be at https://github.com/MomentsLD/moments these days.
